models_to_graph:
  - "std AE"
  - "JPEG"
  - "BPG"
  - "JPEGXL"
  - "denoise+std AE"
  - "denoise+JPEG"
  - "denoise+JPEGXL"
  - "denoise+BPG"
  - JDC-CN
  - JDC-Cn.8
  - Testolina
xrange:
  - 0.09
  - 0.44
yrange:
  - 0.895
  - 0.973
csv_fpath: "../../results/dc/twomodels_test_denoise_q=[0.7,0.999];-bpp-msssim.csv"
legend_ncol: 4
legend_size: 7
# graph_title: "Noisy images compressed with or without prior or joint denoising"
fig_height: 3.8
