models_to_graph:
  - "JDC-N"
  - "JDC-CN"
  - "JDC-Cn.2"
  - "JDC-Cn.4"
  # - "lownoise (.5)"
  - "JDC-Cn.6"
  # - "lownoise (.7)"
  - "JDC-Cn.8"
  # - "lownoise (85)"
  - "JDC-Cn.9"
  - JDC-UD
  - "std AE"
  - "denoise+std AE"
  - "denoise+JPEGXL"
  - "std AE"
  - "JPEG"
  - "BPG"
  - "JPEGXL"
  - "JDC-Cn.8-Tdec"
  #- "testolina"
ignore_std: True
xrange:
  - 0.09
  - 0.401
yrange:
  - 0.93
  - 0.965
csv_fpath: "../../results/dc/twomodels_test_denoise_q=[0.5,0.999];-bpp-msssim.csv"
fig_height: 4.8
