models_to_graph:
  - "JDC-N"
  - "JDC-CN"
  # - "lownoise (20)"
  # - "lownoise (40)"
  # - "lownoise (50)"
  # - "lownoise (60)"
  # - "lownoise (70)"
  - "JDC-Cn.8"
  # - "lownoise (90)"
  - "denoise+std AE"
  - "denoise+JPEG"
  - "denoise+BPG"
  - "denoise+JPEGXL"
  # - "JDC-Cn.8-Tdec"
  - "Testolina"
  - JDC-UD
