- model_name: Noisy
  arch: Passthrough
  train_method: null
  train_lambda: 0
- model_name: Denoised
  arch: Passthrough
  train_method: twomodels
  train_lambda: 0
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- model_name: jpg
  arch: JPEG
  train_method: null
- model_name: jxl
  train_method: null
  arch: JPEGXL
- model_name: bpg
  train_method: null
  arch: BPG
- models_rootdir: dc
  model_name: dctrain_allnoise_nind_fp-L4096-mb-cas101.cism.ucl.ac.be
  train_method: allnoise
  train_lambda: 4096
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_allnoise_nind_fp-L2048-mb-cas001.cism.ucl.ac.be
  train_method: allnoise
  train_lambda: 2048
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_allnoise_nind_fp-L1024-mb-rom103.cism.ucl.ac.be
  train_method: allnoise
  train_lambda: 1024
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_allnoise_nind_fp-L512-mb-rom104.cism.ucl.ac.be  # 96%
  train_method: allnoise
  train_lambda: 512
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_allnoise_nind_fp-L256-mb-rom104.cism.ucl.ac.be  # 98%
  train_method: allnoise
  train_lambda: 256
  lossf: mse
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp-L4096-mb-cas101.cism.ucl.ac.be
#   train_method: lownoise90
#   train_lambda: 4096
#   lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise80_nind_fp-L4096-mb-cas001.cism.ucl.ac.be
  train_method: lownoise80
  train_lambda: 4096
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise80_nind_fp-L2048-mb-rom102.cism.ucl.ac.be
  train_method: lownoise80
  train_lambda: 2048
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise80_nind_fp-L1024-mb-cas001.cism.ucl.ac.be
  train_method: lownoise80
  train_lambda: 1024
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise80_nind_fp-L512-mb-cas101.cism.ucl.ac.be
  train_method: lownoise80
  train_lambda: 512
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise80_nind_fp-L256-mb-rom102.cism.ucl.ac.be
  train_method: lownoise80
  train_lambda: 256
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise50_nind_fp-L4096-mb-cas101.cism.ucl.ac.be
  train_method: lownoise50
  train_lambda: 4096
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise50_nind_fp-L2048-mb-rom102.cism.ucl.ac.be
  train_method: lownoise50
  train_lambda: 2048
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise50_nind_fp-L1024-mb-cas101.cism.ucl.ac.be
  train_method: lownoise50
  train_lambda: 1024
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise50_nind_fp-L512-mb-cas001.cism.ucl.ac.be
  train_method: lownoise50
  train_lambda: 512
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise50_nind_fp-L256-mb-cas001.cism.ucl.ac.be
  train_method: lownoise50
  train_lambda: 256
  lossf: mse
# - models_rootdir: dc  # TODO cmt
#   model_name: dctrain_lownoise80_nind_fp-L2048-mb-cas102.cism.ucl.ac.be
#   train_lambda: 2048
#   lossf: mse
#   train_method: lownoise80
- models_rootdir: dc
  model_name: dctrain_lownoise70_nind_fp-L4096-mb-cas101.cism.ucl.ac.be
  train_method: lownoise70
  train_lambda: 4096
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise70_nind_fp-L2048-mb-cas001.cism.ucl.ac.be
  train_method: lownoise70
  train_lambda: 2048
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise70_nind_fp-L1024-mb-cas001.cism.ucl.ac.be
  train_method: lownoise70
  train_lambda: 1024
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise70_nind_fp-L512-mb-cas101.cism.ucl.ac.be
  train_method: lownoise70
  train_lambda: 512
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise70_nind_fp-L256-mb-cas001.cism.ucl.ac.be
  train_method: lownoise70
  train_lambda: 256
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise60_nind_fp-L4096-mb-cas101.cism.ucl.ac.be
  train_method: lownoise60
  train_lambda: 4096
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise60_nind_fp-L2048-mb-cas101.cism.ucl.ac.be
  train_method: lownoise60
  train_lambda: 2048
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise60_nind_fp-L1024-mb-cas001.cism.ucl.ac.be
  train_method: lownoise60
  train_lambda: 1024
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise60_nind_fp-L512-mb-cas001.cism.ucl.ac.be
  train_method: lownoise60
  train_lambda: 512
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise60_nind_fp-L256-mb-cas101.cism.ucl.ac.be
  train_method: lownoise60
  train_lambda: 256
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise40_nind_fp-L4096-mb-cas101.cism.ucl.ac.be
  train_method: lownoise40
  train_lambda: 4096
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise40_nind_fp-L2048-mb-cas001.cism.ucl.ac.be
  train_method: lownoise40
  train_lambda: 2048
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise40_nind_fp-L1024-mb-rom101.cism.ucl.ac.be  # 71%
  train_method: lownoise40
  train_lambda: 1024
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise40_nind_fp-L512-mb-rom101.cism.ucl.ac.be  # 76%
  train_method: lownoise40
  train_lambda: 512
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise40_nind_fp-L256-mb-cas102.cism.ucl.ac.be  # 79%
  train_method: lownoise40
  train_lambda: 256
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise20_nind_fp-L4096-mb-cas102.cism.ucl.ac.be
  train_method: lownoise20
  train_lambda: 4096
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise20_nind_fp-L2048-mb-cas001.cism.ucl.ac.be
  train_method: lownoise20
  train_lambda: 2048
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise20_nind_fp-L1024-mb-rom101.cism.ucl.ac.be  # 87%
  train_method: lownoise20
  train_lambda: 1024
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise20_nind_fp-L512-mb-cas101.cism.ucl.ac.be  # 94%
  train_method: lownoise20
  train_lambda: 512
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise20_nind_fp-L512-mb-cas101.cism.ucl.ac.be  # 90%
  train_method: lownoise20
  train_lambda: 256
  lossf: mse
- models_rootdir: dc  # test_key = val_denoise_combined_loss
  model_name: dctrain_lownoise_nind_fp-L256-mb-cas101.cism.ucl.ac.be
  train_method: lownoise
  train_lambda: 256
  lossf: mse
- models_rootdir: dc  # test_key = val_denoise_combined_loss
  model_name: dctrain_lownoise_nind_fp-L512-mb-cas102.cism.ucl.ac.be
  train_method: lownoise90
  train_lambda: 512
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp-L1024-mb-cas001.cism.ucl.ac.be
  train_method: lownoise90
  train_lambda: 1024
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp-L2048-mb-cas001.cism.ucl.ac.be
  train_method: lownoise90
  train_lambda: 2048
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_onlynoise_nind_fp-L8192-mb-cas001.cism.ucl.ac.be
  train_method: onlynoise
  train_lambda: 8192
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_onlynoise_nind_fp-L4096-mb-cas101.cism.ucl.ac.be
  train_method: onlynoise
  train_lambda: 4096
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_onlynoise_nind_fp-L2048-mb-rom101.cism.ucl.ac.be  # 74%
  train_method: onlynoise
  train_lambda: 2048
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_onlynoise_nind_fp-L1024-mb-cas101.cism.ucl.ac.be  # 70%
  train_method: onlynoise
  train_lambda: 1024
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_onlynoise_nind_fp-L512-mb-cas001.cism.ucl.ac.be  # 86 %
  train_method: onlynoise
  train_lambda: 512
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_onlynoise_nind_fp-L256-mb-cas101.cism.ucl.ac.be  # 90%
  train_method: onlynoise
  train_lambda: 256
  lossf: mse
- models_rootdir: dc  # TODO cmt (?)
  model_name: dctrain_lownoise_nind_fp_slurm
  train_method: lownoise90
  train_lambda: 4096
- models_rootdir: dc
  model_name: dctrain_predenoised_nind_fp-L4096-benoit-intoPIXPC
  train_lambda: 4096
  train_method: predenoise
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_predenoised_nind_fp-L2048-benoit-intoPIXPC
  train_lambda: 2048
  train_method: predenoise
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_predenoised_nind_fp-L1024-benoit-intoPIXPC
  train_lambda: 1024
  train_method: predenoise
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_predenoised_nind_fp-L512-benoit-intoPIXPC
  train_lambda: 512
  train_method: predenoise
  lossf: mse
- models_rootdir: dc
  model_name: dctrain_predenoised_nind_fp-L256-benoit-intoPIXPC
  train_lambda: 256
  train_method: predenoise
  lossf: mse
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_testolina-L8192-mb-cas101.cism.ucl.ac.be
#   train_lambda: 8192
#   train_method: lownoise_testolina
#   arch: TestolinaManyPriors
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp_testolina80-L8192-mb-rom101.cism.ucl.ac.be
  train_lambda: 8192
  train_method: lownoise_testolina  # 80, 97
  arch: TestolinaManyPriors
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_testolina-L4096-mb-cas001.cism.ucl.ac.be
#   train_lambda: 4096
#   train_method: lownoise_testolina
#   arch: TestolinaManyPriors
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp_testolina80-L4096-mb-cas102.cism.ucl.ac.be
  train_lambda: 4096
  train_method: lownoise_testolina # 80
  arch: TestolinaManyPriors
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_testolina-L2048-mb-cas001.cism.ucl.ac.be
#   train_lambda: 2048
#   train_method: lownoise_testolina
#   arch: TestolinaManyPriors
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp_testolina80-L2048-mb-cas102.cism.ucl.ac.be
  train_lambda: 2048
  train_method: lownoise_testolina  # 80
  arch: TestolinaManyPriors
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_testolina-L1024-mb-rom103.cism.ucl.ac.be
#   train_lambda: 1024
#   train_method: lownoise_testolina
#   arch: TestolinaManyPriors
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp_testolina80-L1024-mb-rom101.cism.ucl.ac.be
  train_lambda: 1024
  train_method: lownoise_testolina
  arch: TestolinaManyPriors
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_testolina-L512-mb-rom103.cism.ucl.ac.be
#   train_lambda: 512
#   train_method: lownoise_testolina
#   arch: TestolinaManyPriors
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp_testolina80-L512-mb-cas101.cism.ucl.ac.be
  train_lambda: 512
  train_method: lownoise_testolina
  arch: TestolinaManyPriors
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_testolina-L256-mb-cas101.cism.ucl.ac.be
#   train_lambda: 256
#   train_method: lownoise_testolina
#   arch: TestolinaManyPriors
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp_testolina80-L256-mb-rom103.cism.ucl.ac.be
  train_lambda: 256
  train_method: lownoise_testolina
  arch: TestolinaManyPriors
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_testolina-L4096-mb-cas102.cism.ucl.ac.be
#   train_lambda: 4096
#   train_method: lownoise_testolina
#   arch: TestolinaManyPriors  # .9 threshold
# - models_rootdir: dc
#   model_name: dctrain_testolina-L16384-mb-cas101.cism.ucl.ac.be
#   train_lambda: 16384
#   train_method: testolina
#   arch: TestolinaHP
- models_rootdir: dc
  model_name: t16384_2
  train_lambda: 16384
  train_method: testolina
  arch: TestolinaHP
# - models_rootdir: dc
#   model_name: dctrain_testolina-L8192-mb-rom104.cism.ucl.ac.be
#   train_lambda: 8192
#   train_method: testolina
#   arch: TestolinaHP
- models_rootdir: dc
  model_name: t8192fs
  train_lambda: 8192
  train_method: testolina
  arch: TestolinaHP
- models_rootdir: dc
  model_name: dctrain_testolina-L4096-mb-rom103.cism.ucl.ac.be
  train_lambda: 4096
  train_method: testolina
  arch: TestolinaHP
- models_rootdir: dc
  model_name: dctrain_testolina-L2048-mb-rom101.cism.ucl.ac.be  # 57
  train_lambda: 2048
  train_method: testolina
  arch: TestolinaHP
- models_rootdir: dc
  model_name: dctrain_testolina-L1024-mb-rom101.cism.ucl.ac.be  # 50%, 48% on 2nd attempt
  train_lambda: 1024
  train_method: testolina
  arch: TestolinaHP
- models_rootdir: dc
  model_name: dctrain_testolina-L512-mb-cas101.cism.ucl.ac.be  # 44%
  train_lambda: 512
  train_method: testolina
  arch: TestolinaHP
- models_rootdir: dc
  model_name: dctrain_testolina-L256-mb-rom103.cism.ucl.ac.be  # 33%
  train_lambda: 256
  train_method: testolina
  arch: TestolinaHP
- models_rootdir: dc
  model_name: dctrain_testolina-L128-mb-cas001.cism.ucl.ac.be  # 30%
  train_lambda: 128
  train_method: testolina
  arch: TestolinaHP
- models_rootdir: compression  # test_key = test_combined_loss
  model_name: mse_4096_b2017manypriors_64pr_16px_adam_2upd_d
  train_method: std
  train_lambda: 4096
  lossf: mse
- models_rootdir: compression
  model_name: mse_2048_b2017manypriors_64pr_16px_adam_2upd
  train_method: std
  train_lambda: 2048
  lossf: mse
- models_rootdir: compression
  model_name: mse_1024_b2017manypriors_64pr_16px_adam_2upd
  train_method: std
  train_lambda: 1024
  lossf: mse
- models_rootdir: compression
  model_name: mse_512_b2017manypriors_64pr_16px_adam_2upd
  train_method: std
  train_lambda: 512
  lossf: mse
- models_rootdir: compression
  model_name: mse_256_b2017manypriors_64pr_16px_adam_2upd
  train_method: std
  train_lambda: 256
  lossf: mse
#- models_rootdir: dc
#  model_name: dctrain_lownoise_nind_fp_msssimft-L128-mb-cas001.cism.ucl.ac.be
#  train_method: lownoise90
#  train_lambda: 128
#  lossf: msssim
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_msssimft-L64-mb-cas001.cism.ucl.ac.be
#   train_method: lownoise90
#   train_lambda: 64
#   lossf: msssim
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_msssim80-L64-mb-rom104.cism.ucl.ac.be  # 63
#   train_method: lownoise80
#   train_lambda: 64
#   lossf: msssim
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_msssim80-L64-mb-cas001.cism.ucl.ac.be
#   train_method: lownoise80
#   train_lambda: 64
#   lossf: msssim
- models_rootdir: dc
  model_name: lownoise80_msssim_2  # 48
  train_method: lownoise80
  train_lambda: 64
  lossf: msssim
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp_msssim80-L32-mb-cas101.cism.ucl.ac.be  # 37
  train_method: lownoise80
  train_lambda: 32
  lossf: msssim  # TODO cmt
# - models_rootdir: dc
#   model_name: dctrain_lownoise_nind_fp_msssim80-L32-mb-rom104.cism.ucl.ac.be # 40
#   train_method: lownoise80
#   train_lambda: 32
#   lossf: msssim
#- models_rootdir: dc
#  model_name: dctrain_lownoise_nind_fp_msssimft-L32-mb-cas001.cism.ucl.ac.be
#  train_method: lownoise80
#  train_lambda: 32
#  lossf: msssim  # TODO cmt
#- models_rootdir: dc
#  model_name: dctrain_lownoise_nind_fp_msssimft-L16-mb-cas001.cism.ucl.ac.be
#  train_method: lownoise80
#  train_lambda: 16
#  lossf: msssim  # TODO cmt
#- models_rootdir: dc
#  model_name: dctrain_lownoise_nind_fp_msssim80-L16-mb-cas001.cism.ucl.ac.be  # didn't reset lr
#  train_method: lownoise80
#  train_lambda: 16
#  lossf: msssim  # TODO cmt
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp_msssim80-L16-mb-rom104.cism.ucl.ac.be  # 50
  train_method: lownoise80
  train_lambda: 16
  lossf: msssim
#- models_rootdir: dc
#  model_name: dctrain_lownoise_nind_fp_msssimft-L8-mb-cas102.cism.ucl.ac.be
#  train_method: lownoise90
#  train_lambda: 8
#  lossf: msssim
- models_rootdir: dc
  model_name: dctrain_lownoise_nind_fp_msssim80-L8-mb-cas101.cism.ucl.ac.be
  train_method: lownoise80
  train_lambda: 8
  lossf: msssim
- models_rootdir: compression
  model_name: msssim_128_b2017manypriors_64pr_16px_adam_2upd_hlr_cont
  train_method: std
  train_lambda: 128
  lossf: msssim
- models_rootdir: compression
  model_name: msssim_64_b2017manypriors_64pr_16px_adam_2upd_hlr_cont
  train_method: std
  train_lambda: 64
  lossf: msssim
- models_rootdir: compression
  model_name: msssim_32_b2017manypriors_64pr_16px
  train_method: std
  train_lambda: 32
  lossf: msssim
- models_rootdir: compression
  model_name: msssim_16_b2017manypriors_64pr_16px
  train_method: std
  train_lambda: 16
  lossf: msssim
- models_rootdir: compression
  model_name: msssim_8_b2017manypriors_64pr_16px_adam_2upd_hlr_cont
  train_method: std
  train_lambda: 8
  lossf: msssim
- models_rootdir: compression  # test_key = test_combined_loss
  model_name: mse_4096_b2017manypriors_64pr_16px_adam_2upd_d
  train_method: twomodels
  train_lambda: 4096
  lossf: mse
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- models_rootdir: compression
  model_name: mse_2048_b2017manypriors_64pr_16px_adam_2upd
  train_method: twomodels
  train_lambda: 2048
  lossf: mse
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- models_rootdir: compression
  model_name: mse_1024_b2017manypriors_64pr_16px_adam_2upd
  train_method: twomodels
  train_lambda: 1024
  lossf: mse
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- models_rootdir: compression
  model_name: mse_512_b2017manypriors_64pr_16px_adam_2upd
  train_method: twomodels
  train_lambda: 512
  lossf: mse
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- models_rootdir: compression
  model_name: mse_256_b2017manypriors_64pr_16px_adam_2upd
  train_method: twomodels
  train_lambda: 256
  lossf: mse
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- model_name: jpg
  arch: JPEG
  train_method: twomodels
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- model_name: jxl
  train_method: twomodels
  arch: JPEGXL
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- model_name: bpg
  train_method: twomodels
  arch: BPG
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- models_rootdir: compression
  model_name: msssim_128_b2017manypriors_64pr_16px_adam_2upd_hlr_cont
  train_method: twomodels
  train_lambda: 128
  lossf: msssim
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- models_rootdir: compression
  model_name: msssim_64_b2017manypriors_64pr_16px_adam_2upd_hlr_cont
  train_method: twomodels
  train_lambda: 64
  lossf: msssim
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- models_rootdir: compression
  model_name: msssim_32_b2017manypriors_64pr_16px
  train_method: twomodels
  train_lambda: 32
  lossf: msssim
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- models_rootdir: compression
  model_name: msssim_16_b2017manypriors_64pr_16px
  train_method: twomodels
  train_lambda: 16
  lossf: msssim
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
- models_rootdir: compression
  model_name: msssim_8_b2017manypriors_64pr_16px_adam_2upd_hlr_cont
  train_method: twomodels
  train_lambda: 8
  lossf: msssim
  quality_whole_csv_fpath: ../../datasets/NIND-msssim_denoisedpaths.csv
