- prefix: test_denoise_q=[0.7,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.5,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.85,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.85,0.999];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.9,0.999];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.95,0.999];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.9,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.95,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.3,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.2,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.4,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.6,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.1,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.8,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.8,0.999];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.7,0.999];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0,0.999];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0,0.999];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.7,0.8];
  xaxis: bpp
  yaxis: msssim
- prefix: test_clic_pro
  xaxis: bpp
  yaxis: psnr
- prefix: test_clic_pro
  xaxis: bpp
  yaxis: msssim
- prefix: kodak
  xaxis: bpp
  yaxis: psnr
- prefix: kodak
  xaxis: bpp
  yaxis: msssim
- prefix: Commons_Test_Photographs
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=1.00;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=.99;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=.98;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=.97;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=.96;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=.95;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=.90;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=1.00;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=.99;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=.98;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=.97;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=.96;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=.95;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=.90;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.9,1.00];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.95,1.00];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.9,0.95];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.9,1.00];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.95,1.00];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.9,0.95];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=.80;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=.80;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.8,0.9];
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q=[0.8,0.9];
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=70;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=60;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=50;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=0;
  xaxis: bpp
  yaxis: psnr
- prefix: test_denoise_q>=70;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=60;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=50;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q>=0;
  xaxis: bpp
  yaxis: msssim
- prefix: test_denoise_q=[0.7,0.8];
  xaxis: bpp
  yaxis: psnr
# - prefix: Commons_Test_Photographs
#   xaxis: bpp
#   yaxis: msssim
# - prefix: cat
#   xaxis: bpp
#   yaxis: psnr
# - prefix: cat
#   xaxis: bpp
#   yaxis: msssim
