python tools/graph_res.py --fig_height 7.8
cd /orb/benoit_phd/results/dc
cp onecat-bpp-msssim.csv.pdf '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp  twomodels_kodak-bpp-msssim.csv.pdf '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp  twomodels_test_clic_pro-bpp-msssim.csv.pdf '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0,0.999];-bpp-psnr.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.1,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.2,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.3,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.4,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.5,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.6,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.7,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.7,0.999];-bpp-psnr.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.8,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.8,0.999];-bpp-psnr.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.85,0.999];-bpp-psnr.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.9,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.9,0.999];-bpp-psnr.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.95,0.999];-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q=[0.95,0.999];-bpp-psnr.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
cp 'twomodels_test_denoise_q>=1.00;-bpp-msssim.csv.pdf' '/orb/benoit_phd/wiki/Papers/compdenoise/figures/suppl/'
